name: Scorecards

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 1 * * 0'

jobs:
  analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: ossf/scorecard-action@v2.2.0
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
